export const metadata = {
    title: "Search | OpenTables",
    description: "Generated by create next app",
  };
export default function Head() {
  return (
    <>
      <title>Searceh | OpenTable</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
