import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";
import { PrismaClient, Cuisine, Location, PRICE, Review } from "@prisma/client";

export interface RestaurantCardType {
  id: number;
  name: string;
  main_image: string;
  cuisine: Cuisine;
  location: Location;
  price: PRICE;
  slug: string;
  reviews: Review[];
}

const prisma = new PrismaClient();

const fetchRestaurants = async (): Promise<RestaurantCardType[]> => {
  const restaurants = await prisma.restaurant.findMany({
    select: {
      id: true,
      name: true,
      main_image: true,
      cuisine: true,
      slug: true,
      location: true,
      price: true,
      reviews: true,
    },
  });

  return restaurants;
};

export const metadata = {
  title: "Home | OpenTables",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  const restaurants = await fetchRestaurants();

  // console.log("-----IM IN THE DEFAULT HOME PAGE");
  // const secret = new TextEncoder().encode(process.env.JWT_SECRET);
  // console.log(secret, "------ @HOME PAGE!!!");
  // const testing = process.env.TEST_VARIABLE;
  // console.log(testing, "------ @TESTING PAGE!!!");
  return (
    <main>
      <Header />
      <div className="py-3 px-36 mt-10 flex flex-wrap justify-center">
        {restaurants.map((restaurant) => (
          <RestaurantCard key={restaurant.id} restaurant={restaurant} />
        ))}
      </div>
    </main>
  );
}

//pass db: 9fsgr4ftDoVe8xq9